import java.util.function.UnaryOperator

var numbers=listOf<Int>(1,2,3)
println(numbers.get(1))
println("indexOf"+numbers.indexOf(1))
println(numbers.listIterator())
println(numbers.listIterator(1))
println(numbers.last())
println(numbers.first())
println("===============")

var numbers2=mutableListOf<Int>(1,2,3)
println(numbers2.add(0,0))
println(numbers2.add(50))
println(numbers2.removeAt(1))
numbers2.addAll(0,setOf<Int>(10,20,30))
println(numbers2)
println("============================")

val numbers3=setOf<Int>(1,1,1,1,3,2)
println(numbers3.contains(2))
println(numbers3.containsAll(setOf<Int>(1,3)))
val numbers4=mutableSetOf<Int>(1,3)
numbers4.remove(1)
println(numbers4)
println("===========================")

val numbers5=mapOf<Int,String>(1 to "one",2 to "two",3 to "three")
println(numbers5.keys)
println(numbers5[1])
println(numbers5.values)
println(numbers5.size)
println(numbers5.get(2))
println(numbers5[1])
println(numbers5.getOrDefault(4,"키4는 없음"))
val numbers6=mapOf<Int,String>(Pair(1,"one"),Pair(2,"two"))
